CREATE USER "FRC" WITH PASSWORD 'Fran120513';
CREATE DATABASE "Clinica" WITH OWNER = "FRC";

\c "Clinica"

CREATE TABLE IF NOT EXISTS ips (
    ip_address VARCHAR(45) PRIMARY KEY NOT NULL,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ips (ip_address) VALUES ('81.61.220.22');
INSERT INTO ips (ip_address) VALUES ('81.44.40.172');

